; Generated by Delta Compiler
; Input File: C:\Users\terra\Documents\Projekte\delta-lang\examples\native_test\structs.dltu
; Compiler Arguments: -filetype=obj
; Linker Arguments:  -luser32 -lgdi32 -lkernel32 -lopengl32
; ModuleID = 'delta_program'
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

; External function declarations


%struct.Foo = type { float, i32, double }

define i32 @main() {
entry:
  %t0 = alloca %struct.Foo, align 1; Allocate variable "val"
  store %struct.Foo { float 0x40091EB860000000, i32 42, double 0x402E000000000000 }, %struct.Foo* %t0, align 1; Set variable "val"
  ret i32 0
}

