; Generated by Delta Compiler
; Input File: example.dlt
; llc Arguments: -filetype=obj
; ModuleID = 'delta_program'
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

; External function declarations
declare void @exit(i32)
declare void @free(i8*)
declare i8* @malloc(i64)
declare i32 @printf(i8*)
declare i8* @strcpy(i8*, i8*)
declare i64 @strlen(i8*)

define i32 @main() {
entry:
  %t0 = alloca i8, align 1; Allocate variable "x"
  store i8 72, i8* %t0, align 1; Set variable "x"
  %t1 = load i8, i8* %t0, align 1 ; Use Variable x
  %t2 = sext i8 %t1 to i32 ; Int Sign Extend
  ret i32 %t2 ; Return
  ret i32 0
}

