; Generated by Delta Compiler
; Input File: example.dlt
; Nasm Arguments: -f win64
; Link Arguments: /subsystem:console /entry:_start /defaultlib:kernel32.lib /defaultlib:msvcrt.lib
global _start
extern ExitProcess

section .text
_start:
	mov rax, 3
	push rax
	mov rax, 3
	push rax
	pop rax
	pop rbx
	mul rbx
	push rax
	mov rax, 1
	push rax
	pop rcx
	call ExitProcess
	mov rcx, 0
	call ExitProcess
