#include "Compiler.h"
#include "Log.h"
#include "Files.h"
#include "Tokenizer.h"
#include "Preprocessor.h"
#include "Parser.h"
#include "Assembler.h"
#include "Error.h"
#include "Debug.h"
#include <fstream>

namespace Delta
{

    int Compiler::compile(const CompilerProperties &props)
    {
        Log::setVerbose(props.verbose);
        std::string inputPath = Files::getAbsolutePath(props.inputFile);
        std::string outputPath = Files::getAbsolutePath(props.outputFile);
        LOG_INFO("Compiling {}...", inputPath);
        LOG_TRACE("Compile Type: {}", getCompileTypeName(props.compileType));

        if (!Files::fileExists(inputPath))
        {
            LOG_ERROR("Input file does not exist: {}", inputPath);
            return 1;
        }

        std::string programPath = Files::getDirectory(Files::getProgramPath());
        std::string llcLink = Files::joinPaths(programPath, "llc.exe");
        if (!Files::fileExists(llcLink))
        {
            LOG_ERROR("LLVM Compiler executable not found at: {}", llcLink);
            return 1;
        }

        std::string linkPath = Files::joinPaths(programPath, "clang.exe");
        if (!Files::fileExists(linkPath))
        {
            LOG_ERROR("Linker executable not found at: {}", linkPath);
            return 1;
        }

        std::string stdlibPath = Files::joinPaths(programPath, "stdlib.lib");
        if (!Files::fileExists(stdlibPath))
        {
            LOG_ERROR("Standard Library not found at: {}", stdlibPath);
            return 1;
        }

        std::string contents = Files::readFile(inputPath);
        if (contents.empty())
        {
            LOG_ERROR("Failed to read input file or file is empty: {}", inputPath);
            return 1;
        }

        std::string assembly = "";

        std::string intDir = Files::joinPaths(Files::getDirectory(outputPath), "int");
        if (!Files::fileExists(intDir))
        {
            if (!Files::createDirectory(intDir))
            {
                LOG_ERROR("Failed to create intermediate directory: {}", intDir);
                return 1;
            }
        }
        auto writeParseFile = [&](const std::string &parseFile, const std::string &content) -> bool
        {
            if (!Files::writeFile(parseFile, content))
            {
                LOG_ERROR("Failed to write intermediate file: {}", parseFile);
                return false;
            }
            return true;
        };
        auto writeAsmFile = [&](const std::string &asmFile) -> bool
        {
            if (!Files::writeFile(asmFile, assembly))
            {
                LOG_ERROR("Failed to write intermediate file: {}", asmFile);
                return false;
            }
            return true;
        };

        auto runCommand = [&](const std::string &cmd) -> bool
        {
            LOG_TRACE("Running command: cmd /C {}", cmd);
            if (std::system(("cmd /C " + cmd).c_str()) != 0)
            {
                LOG_ERROR("Failed to execute command: {}", cmd);
                return false;
            }
            return true;
        };

        // Generate file paths
        std::string baseName = Files::getFileNameWithoutExtension(inputPath);
        std::string parseFile = Files::joinPaths(intDir, baseName + ".ast.txt");
        std::string asmFile = Files::joinPaths(intDir, baseName + ".ll");
        std::string objFile = Files::joinPaths(intDir, baseName + ".obj");

        std::string llcArguments = "-filetype=obj";
        std::string linkArguments = "-nodefaultlibs";

        std::string assemblyPrefix = "; Generated by Delta Compiler\n";
        assemblyPrefix += "; Input File: " + std::string(inputPath) + "\n";

#ifdef _WIN32
        linkArguments += " -luser32 -lgdi32 -lkernel32";
#else
        linkArguments += " -lX11";
#endif

#ifdef _WIN32
        std::string linkOutputFlag = " -o " + std::string(outputPath);
#else
        std::string linkOutputFlag = " -o " + std::string(outputPath);
#endif

        Tokenizer tokenizer(contents);
        std::vector<Token> tokens = tokenizer.tokenize();
        Preprocessor processor(tokens);
        std::vector<Token> processedTokens = tokenizer.tokenize();
        Parser parser(processedTokens);
        auto parseTree = parser.parseProgram();
        if (parseTree.has_value())
        {
            writeParseFile(parseFile, nodeDebugPrint(parseTree.value()));
            Assembler assembler(parseTree.value());
            assembly = assembler.generate();
            assembly = assemblyPrefix + assembly;
        }
        else
        {
            LOG_ERROR("Invalid Program");
            return 1;
        }

        switch (props.compileType)
        {
        case COMPILE_ONLY:
        {
            if (!writeAsmFile(asmFile))
                return 1;
            std::string command = "\"" + llcLink + "\" " + llcArguments + " " + asmFile + " -o " + outputPath;
            if (!runCommand(command))
                return 1;
            break;
        }
        case COMPILE_AND_LINK:
        {
            if (!writeAsmFile(asmFile))
                return 1;
            std::string assembleCommand = "\"" + llcLink + "\" " + llcArguments + " " + asmFile + " -o " + objFile;
            if (!runCommand(assembleCommand))
                return 1;

            std::string linkCommand = "\"" + linkPath + "\" " + objFile + " " + stdlibPath + linkOutputFlag + " " + linkArguments;

            if (!runCommand(linkCommand))
                return 1;
            break;
        }

        case COMPILE_LINK_AND_RUN:
        {
            if (!writeAsmFile(asmFile))
                return 1;
            std::string assembleCommand = "\"" + llcLink + "\" " + llcArguments + " " + asmFile + " -o " + objFile;
            if (!runCommand(assembleCommand))
                return 1;

            std::string linkCommand = "\"" + linkPath + "\" " + objFile + " " + stdlibPath + linkOutputFlag + " " + linkArguments;

            if (!runCommand(linkCommand))
                return 1;

            std::string runCommandStr = "\"" + std::string(outputPath) + "\"";
            LOG_INFO("Running command: {}", runCommandStr);
            int exitCode = std::system(runCommandStr.c_str());
            LOG_INFO("Program exited with code: {}", exitCode);
            break;
        }
        }

        return 0;
    }
}